### ISSUE TITLE
Crashes on death

### ISSUE THREAD

**Issue by freeeranger** [Maciej916/Ma-Enchants#6] opened 2019-12-04 15:23 UTC
**Describe the bug**
When I get killed by a skeleton or by fall damage, the game crashes.

**To Reproduce**
1. Create a new world.
2. Get killed by a skeleton OR get killed by fall damage
3. The game will crash.

**Expected behavior**
I expected the game not to crash when I die.

**Versions**
- **Ma Enchants**: 1.6.1
- **Forge**: 28.1.96

**Additional context**
Here's the crash log: https://pastebin.com/G317CwwY

**Comment by slowiu06** [comment] 2019-12-04 19:46
Propably the same problem here, this time caused by falling damage. 

https://paste.dimdev.org/yucaliripi.rb

**Comment by Maciej916** [comment] 2019-12-05 09:08
Fixed in [v1.6.2](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/2836964)

**Comment by freeeranger** [comment] 2019-12-06 15:02
Same issue again...
Killed by a skeleton again, the game crashed, identical crash log.

**Comment by Maciej916** [comment] 2019-12-07 21:59
Ill investigate that

**Comment by Maciej916** [comment] 2019-12-16 14:44
Fixed in [v1.6.3](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/2838292)

**Closed as completed by Maciej916** 2019-12-16 14:44 UTC
Labels: bug
